services:
  backend:
    build:
      context: .
    container_name: backend
    volumes:
      - ./backend/db/storage:${APP_ROOT}/backend/db/storage
      - ./backend/db/backups:${APP_ROOT}/backend/db/backups
      - ./frontend/build:/app/frontend/build
    restart: always
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    network_mode: host
    depends_on:
      - db
      - chromedriver

  db:
    image: postgres:17
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/postgresql/data

  chromedriver:
    image: spryker/chromedriver
    init: true
    container_name: chromedriver
    expose:
      - "${CHROMEDRIVER_PORT}"
    restart: unless-stopped

volumes:
  db_data:

