[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.13.0"
dotenvy = "0.15.7"
image = "0.25.5"
rand = "0.9.0"
sqlx = { version = "0.8.3", features = ["postgres"] }
tokio = "1.43.0"
futures = "0.3.31"
bytes = "1.10.0"